// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://medzlgbjunwtlvglgnhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZHpsZ2JqdW53dGx2Z2xnbmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTk5OTYsImV4cCI6MjA2NzM5NTk5Nn0.K6_Ec7ENnCa9QoidhU9gVib7X5tkT-t7WfTRP3xeZgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});